// Normalise the cut-outs into one shape of frame.
//
// Why: the browser should not be doing arithmetic to make a lying dog and a
// standing dog the same size. Baking it here means every frame has identical
// dimensions, the dog sits on the same floor line, and her centre lands in the
// same place — so changing pose can never make her jump or change size.
//
// Source sprites are read-only: this writes new files into assets/frames/.
import { createRequire } from 'node:module';
import { readFile, writeFile, mkdir, rm } from 'node:fs/promises';
import { join } from 'node:path';

const require = createRequire(import.meta.url);
const sharp = require('D:/DeepSeekHarness/DSH Desktop/resources/app/node_modules/sharp');

const ROOT = 'D:/桌宠';
const SPRITES = join(ROOT, 'assets', 'cutout');
const OUT = join(ROOT, 'assets', 'frames');
const RECIPE = join(ROOT, 'tools', 'normalize.recipe.json');

const recipe = JSON.parse(await readFile(RECIPE, 'utf8'));
const { paddingX, paddingTop, paddingFloor } = recipe.canvas;
const entries = Object.entries(recipe.frames);

/** The height a pose renders at when its scale is 1. Mirrors PET_BASE_HEIGHT in the browser half. */
const BASE_HEIGHT = 300;

/** Resize one sprite to its calibrated size, keeping the alpha intact. */
async function scaled(id, spec) {
  const file = join(SPRITES, spec.src);
  // Scale is relative to the shared base height, NOT to the sprite's own pixel
  // size — otherwise a large source photograph would silently dominate the canvas.
  const height = Math.max(1, Math.round(BASE_HEIGHT * spec.scale));
  const buffer = await sharp(file).resize({ height }).png().toBuffer();
  const meta = await sharp(buffer).metadata();
  return { id, buffer, width: meta.width, height: meta.height };
}

const prepared = [];
for (const [id, spec] of entries) prepared.push(await scaled(id, spec));

// One canvas for everything: sized to the largest pose, so no frame is clipped.
const maxW = Math.max(...prepared.map((p) => p.width));
const maxH = Math.max(...prepared.map((p) => p.height));
const canvasW = maxW + paddingX * 2;
const canvasH = maxH + paddingTop + paddingFloor;
const floorY = canvasH - paddingFloor;

await rm(OUT, { recursive: true, force: true });
await mkdir(OUT, { recursive: true });

/** Where the dog sits inside the canvas, for each frame. */
const placements = {};
for (const piece of prepared) {
  const left = Math.round((canvasW - piece.width) / 2);
  const top = floorY - piece.height;
  placements[piece.id] = { left, top, width: piece.width, height: piece.height };
  await sharp({
    create: { width: canvasW, height: canvasH, channels: 4, background: { r: 0, g: 0, b: 0, alpha: 0 } },
  })
    .composite([{ input: piece.buffer, left, top }])
    .png({ compressionLevel: 9 })
    .toFile(join(OUT, `${piece.id}.png`));
  console.log(`${piece.id.padEnd(12)} ${String(piece.width).padStart(4)}x${String(piece.height).padEnd(4)} -> canvas ${canvasW}x${canvasH} at (${left}, ${top})`);
}

// The manifest exists so the plugin never has to guess where the dog is. Her
// interactive area is this box, not the whole canvas: the transparent margin
// around her must stay click-through, or she would swallow clicks meant for the
// application behind her.
await writeFile(
  join(OUT, 'manifest.json'),
  `${JSON.stringify({ canvas: { width: canvasW, height: canvasH }, floorY, frames: placements }, null, 2)}\n`,
);

await writeFile(
  join(OUT, 'README.txt'),
  [
    'Normalised frames, generated by tools/normalize.mjs from tools/normalize.recipe.json.',
    '',
    `Every frame is ${canvasW}x${canvasH}.`,
    `The floor line is at y=${floorY}; the pet's centre is at x=${Math.round(canvasW / 2)}.`,
    'The dog is the same size in each frame, already corrected for posture and distance.',
    '',
    'Do not hand-edit these: change the scale in tools/normalize.json and re-run the tool.',
    'Source sprites live in assets/cutout/ and are never modified.',
  ].join('\n'),
);
console.log(`\ncanvas ${canvasW}x${canvasH}, floor y=${floorY}, centre x=${Math.round(canvasW / 2)}`);
console.log(`wrote ${prepared.length} frames to ${OUT}`);
